### ISSUE TITLE
Fix documentation test action failing 

### ISSUE THREAD

**Issue by pramodya-rajapakse** [CSE-112-Team-7/Stargazer-V2#10]
**Give a detailed description on the tasks and lay out each expectation for that task in a clear and concise manner**

Tests failing on every push because the action on documentation is expecting the old documentation repo, asking for a token

**ETA: give a rough time estimate to complete this issue** 3-4 days

**Additional Information?** 
<img width="514" alt="image" src="https://github.com/CSE-112-Team-7/Stargazer-V2/assets/102259936/d883eac3-8c29-48d6-bfe1-4d1158b85618">
not sure if we need to make a separate documentation repo, or use the existing one if possible

**Comment by colecarter96** [comment]
We changed token and created our own Github Docs Repo
