### ISSUE TITLE
History Page

### ISSUE THREAD

**Issue by Barak-Horowitz** [CSE-112-Team-7/Stargazer-V2#12]
construct a page that displays all of a user's previous horoscopes, and constellations as well as the date/time they were taken.
- [x] make a button on the index page that redirects a user to their history page 
- [x] Construct a wireframe for how the finalized history page will look 
- [x] display info pulled from a centralized database to display on page

**ETA: give a rough time estimate to complete this issue**
9 days

**Additional Information?**

**Comment by a0-ye** [comment]
![image](https://github.com/CSE-112-Team-7/Stargazer-V2/assets/114363008/888d407c-b668-4a63-9437-3b29e4d429db)

**Comment by a0-ye** [comment]
Figma diagram
![image](https://github.com/CSE-112-Team-7/Stargazer-V2/assets/114363008/e9f6db46-8af9-4637-a6a2-f07601fd9618)
