### ISSUE TITLE
Look into user history

### ISSUE THREAD

**Issue by pramodya-rajapakse** [CSE-112-Team-7/Stargazer-V2#5]
**Give a detailed description on the tasks and lay out each expectation for that task in a clear and concise manner**
Research different ways we could implement user history
- [x] how to store user data: database (which ones), cookies, local storage, etc
- [ ] challenges, benefits, limitations of each option

**ETA: give a rough time estimate to complete this issue:** 3-4 days

**Additional Information?**
- should make an ADR during the next meeting about which option we chose

**Comment by jphung101** [comment]
- [ ] Fortune
- [ ] Time/date of creation
- [ ] Constellation
- [ ] Category
- [ ] Summary page of all fortune (LATER)
